use NYPD;

DROP TABLE Weather;

CREATE TABLE Weather(
  STATION_NAME varchar(100) DEFAULT NULL,
  W_DATE varchar(100) DEFAULT NULL,
  PRCP varchar(100) DEFAULT NULL,
  SNWD varchar(100) DEFAULT NULL,
  SNOW varchar(100) DEFAULT NULL,
  TSUN varchar(100) DEFAULT NULL,
  TAVG varchar(100) DEFAULT NULL,
  TMAX varchar(100) DEFAULT NULL,
  TMIN varchar(100) DEFAULT NULL,
  AVG_WND varchar(100) DEFAULT NULL,
  FOG_IC_FF varchar(100) DEFAULT NULL,
  IF_FFOG varchar(100) DEFAULT NULL,
  HF_HFFOG varchar(100) DEFAULT NULL,
  HW_DWIND varchar(100) DEFAULT NULL,
  SM_HAZE varchar(100) DEFAULT NULL,
  HAIL varchar(100) DEFAULT NULL,
  I_S_PELLETS varchar(100) DEFAULT NULL,
  SNOW_IC varchar(100) DEFAULT NULL,
  DRIZZLE varchar(100) DEFAULT NULL,
  RAIN varchar(100) DEFAULT NULL,
  MIST varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DELETE FROM Weather;

LOAD DATA LOCAL INFILE '/Users/vipinarora/Desktop/Weather.csv' 
INTO TABLE Weather 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r';